### ISSUE TITLE
关于速度的疑问

### ISSUE THREAD

**Issue by chenxyyy** [Reverie10/PointPillars_MultiHead_40FPS#17]
你好， 我想问一下，pointpillar原本不就是30+ms嘛，为什么您这边用了tensorrt后依然耗时27.5ms呢，为什么效果没有那么明显呢？

**Comment by hova88** [comment]
> 你好， 我想问一下，pointpillar原本不就是30+ms嘛，为什么您这边用了tensorrt后依然耗时27.5ms呢，为什么效果没有那么明显呢？

你好，不同参数配置的pointpillar性能是不一样的，你可以做个实验，对比看看我这个配置的在不使用tensorrt的情况下耗时大概是多少，我没有详细对比。
