### ISSUE TITLE
How to train my own dataset(with three categories),thanks!

### ISSUE THREAD

**Issue by HaoGe30** [Reverie10/PointPillars_MultiHead_40FPS#19]
I also encounter some problems when try to utilize this project on my own datasets.The format of my datasets is the way Openpcdet needs and I have transfered it to kitti format.It is trained well on 3 categories(car,pedestrain,cyclist) just with little changes on "cfgs/kitti_models/pointpillar.yaml".But when I try to apply my own datasets with cbgs_pp_multihead.yaml then something goes wrong.I think the problem is the different between nuscences and kitti and the change of the number of categories. Can you give me some hint of how to change cbgs_pp_multihead.yaml to train my datasets（3 categories）.Thanks!

**Comment by HaoGe30** [comment]
I have solved my problem. Just a reminder for thoese who want to train their own datasets,code_size is related to REG_LIST in config file,feature_map_stride should be 4 if UPSAMPLE_STRIDES is [0.5, 1, 2] and be 2 if UPSAMPLE_STRIDES is [1, 2, 4] to match between predictions and targets.Check source code is the best way to solve problem and I learn it from  this experience.Thanks authors for sharing the code.

**Comment by DeepBehavier** [comment]
麻烦问下，code_size和REG_LIST是什么关系？kitti和nuscenses数据集，REG_LIST是否不一样？

**Comment by jlqzzz** [comment]
@HaoGe30 

Can you give me more details of how to change cbgs_pp_multihead.yaml to train my datasets (3 categories), or can you share your successful yaml files?

Thanks!
